import "~/styles/globals.css";

import { Montserrat } from "next/font/google";

import type { Metadata } from "next";
import Providers from "../components/Providers";

export const metadata: Metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const montserrat = Montserrat({
  subsets: ["latin"],
  variable: "--font-montserrat",
});

export default async function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${montserrat.variable}`}>
      <body className="flex min-h-screen flex-col">
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
